### ISSUE TITLE
Как встроить слой доступа?

### ISSUE THREAD

**Issue by Crysp** [bespoyasov/explicit-design#1]
Прекрасная серия статей по архитектуре 👍

Когда я начал примерять этот подход на свое приложение, столкнулся с проблемой авторизации.

Во-первых что я понимаю под авторизацией — часть кода которая отвечает за получение и обновление токена доступа (не более).

Авторизация затрагивает все приложение: токен доступа передается при запросах в API, необходимо проверять его наличие прежде чем вызывать юзкейсы. Поскольку она настолько глобальна, думаю будет правильным положить в `services` с такими ручками:

```typescript
export type CreateAccessToken = () => Promise<string>
export type GetAccessToken = () => string;
export type RefreshAccessToken = () => Promise<string>
```

Далее передать его в запрос API можно в самой фиче:

**/features/notes/infrastructure/api**
```typescript
const getNotes = createGetNotes({ request, getAccessToken, refreshAccessToken });
```

Но не понятно как наличие доступа работает с юзкейсами. [Поскольку это не бизнес логика](https://stackoverflow.com/questions/23464697/access-control-in-domain-driven-design), то проверять токен внутри юзкейса не правильно. На сколько я понял выше юзкейса находится UI, а там эту проверку думаю не стоит делать. Плюс есть юзкейсы которые запускаются по событиям, получается надо где-то отлавливать нужные события и создавать новые "авторизованные события".

Буду рад любым референсам где можно подчерпнуть информации по этому поводу

**Comment by bespoyasov** [comment]
Привет, спасибо!

> Авторизация затрагивает все приложение

Да, поэтому её можно (не обязательно, но можно) воспринимать как cross-cutting concern, внедряя функциональность через декораторы:

```ts
function withAuth<F extends AnyAsyncFn>(fn: F) {
  return async function perform(...args: Parameters<F>): ReturnType<F> {
    // ...Аутентификация, проверка токена и т.д.
    // ...Вызов самой fn.
  }
}

const createUser = withAuth(async () => {/*...*/})
```

С точки зрения архитектуры обходиться с аутентификацией можно по-разному. Это может быть [cross-cutting concern](https://en.wikipedia.org/wiki/Cross-cutting_concern), или «сервис», а может быть и отдельный «модуль», [входной порт](https://herbertograca.com/2017/11/16/explicit-architecture-01-ddd-hexagonal-onion-clean-cqrs-how-i-put-it-all-together/#ports) которого — это, например, такой декоратор или компонент, который рендерит потомков, только если пользователь аутентифицирован.

Тут советовать сложно, потому что конкретное решение будет зависеть от флоу аутентификации, сложности и разношёрстности юзкейсов (это как раз случай «Плюс есть юзкейсы которые запускаются по событиям, получается надо где-то отлавливать нужные события и создавать новые "авторизованные события"») и предпочтений команды насчёт публичного API и [степени зацепления](https://youtu.be/jyX7nt1wQwg?si=cTHNSOpNQXRFwMqg) между модулями.

(В некоторых случаях может быть использовать «событийную модель» и бросаться событиями или сообщениями, чтобы запустить другой юзкейс или другую часть, хотя чаще всего это оверкил.)

В своих проектах у аутентификации я стараюсь разделять «сервисную» функциональность (которая отвечает за непосредственный вызов провайдера, например, чтобы токен получить) и «интеграционную» (которая склеивает её с остальным приложением). 

Не всегда, но бывает, что первая становится «сервисом», а вторая — «композицией». Но опять же зависит от задачи 😃
